### ISSUE TITLE
✨ feat: 가장 최근에 작성한 일기의 id값 조회 기능 개발

### ISSUE THREAD

**Issue by wlaud2000** [LikeLion12-Team3/Team3-Back#50]
# Title

- 가장 최근에 작성한 일기의 id값 조회 기능 개발

# TODO

- [x] DiaryRepository에 가장 최근 작성된 일기의 ID를 조회하는 쿼리 추가
- [x] Service에서 메서드 호출
- [x] Controller에 엔드포인트 추가

# etc
